### ISSUE TITLE
ModuleNotFoundError: No module named 'dockerfile_parse'

### ISSUE THREAD

**Issue by sobolevn** [jeromepin/whale-linter#19]
I have just downloaded your module via `pip install whale-linter`.
Installed it inside a `virtualenv`, and then: `whale-linter my/location/Dockerfile`. Here's the result:
```
» whale-linter docker/django/Dockerfile 
Traceback (most recent call last):
  File "/Users/sobolev/.virtualenvs/test_project-c7lHFdaF/bin/whale-linter", line 3, in <module>
    import whalelinter
  File "/Users/sobolev/.virtualenvs/test_project-c7lHFdaF/lib/python3.6/site-packages/whalelinter/__init__.py", line 6, in <module>
    from whalelinter.parser    import Parser
  File "/Users/sobolev/.virtualenvs/test_project-c7lHFdaF/lib/python3.6/site-packages/whalelinter/parser.py", line 6, in <module>
    from dockerfile_parse import DockerfileParser
ModuleNotFoundError: No module named 'dockerfile_parse'
```

Versions:
- `python==3.6.2`
- `pip==9.0.1`
- `whale-linter==0.0.7`
- `macos==10.11.6`

**Comment by sobolevn** [comment]
You are missing requirements in `setup.py`. PR is coming.
