### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by arthurzenika** [jeromepin/whale-linter#24]
```
Traceback (most recent call last):
  File "/tmp/example/.tox/dockerlint/bin/whale-linter", line 5, in <module>
    whalelinter.run()
  File "/tmp/example/.tox/dockerlint/lib/python3.6/site-packages/whalelinter/__init__.py", line 49, in run
    checker.check()
  File "/tmp/example/.tox/dockerlint/lib/python3.6/site-packages/whalelinter/checker.py", line 20, in check
    dispatcher.react(line)
  File "/tmp/example/.tox/dockerlint/lib/python3.6/site-packages/whalelinter/dispatcher.py", line 35, in react
    docker_command.arguments, docker_command.line)
  File "/tmp/example/.tox/dockerlint/lib/python3.6/site-packages/whalelinter/token.py", line 108, in __init__
    self.labels = {l.split('=')[0]: l.split('=')[1] for l in self.payload}
  File "/tmp/example/.tox/dockerlint/lib/python3.6/site-packages/whalelinter/token.py", line 108, in <dictcomp>
    self.labels = {l.split('=')[0]: l.split('=')[1] for l in self.payload}
IndexError: list index out of range
```

**Comment by jeromepin** [comment]
Hi @arthurlogilab 

Can you provide the associated Dockerfile ?

**Comment by arthurzenika** [comment]
Hi, I think the following is enough to get reproduce the bug : 

```
FROM debian:buster-slim
LABEL maintainer "Logilab <contact@logilab.fr>" \
    org.label-schema.vendor = "Logilab"
```

**Comment by arthurzenika** [comment]
Replacing it by 

```
LABEL maintainer="Logilab <contact@logilab.fr>"
LABEL org.label-schema.vendor="Logilab"
```

Seems to fix it, but it would be nice for whale-linter to find this.
