### ISSUE TITLE
STOPSIGNAL causes exception

### ISSUE THREAD

**Issue by tonymillion** [jeromepin/whale-linter#25]
```
$ whale-linter Dockerfile                                                                                                   2 ↵

Traceback (most recent call last):
  File "<snip>/whale-linter", line 5, in <module>
    whalelinter.run()
  File "<snip>/whale-linter/lib/python3.7/site-packages/whalelinter/__init__.py", line 49, in run
    checker.check()
  File "<snip>/whale-linter/lib/python3.7/site-packages/whalelinter/checker.py", line 20, in check
    dispatcher.react(line)
  File "<snip>/whale-linter/lib/python3.7/site-packages/whalelinter/dispatcher.py", line 33, in react
    if (self._callbacks[docker_command.instruction]['self'] is not None):
KeyError: 'STOPSIGNAL'
```

"offending Dockerfile"

```
# syntax=docker/dockerfile:experimental
FROM python:3-alpine AS build

#First make a place on the container filesystem for the code to live
RUN mkdir /server
WORKDIR /server

<etc etc>

WORKDIR /server
EXPOSE 8000
STOPSIGNAL SIGTERM
ENTRYPOINT [ "sh" ]

CMD [ "/server/start_server.sh" ]
```

`STOPSIGNAL` is used to change the signal that is sent to the entry point to tell it to shutdown. https://docs.docker.com/engine/reference/builder/#stopsignal

**Comment by tonymillion** [comment]
Fixed in #26
